name: Validate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Validate HACS structure
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Validate Home Assistant integration
        uses: home-assistant/actions/hassfest@e3fb68ebda13d88a0d695082f471ba2c83d025fb
